### ISSUE TITLE
Loadbalancing needs to account for non-neighbouring connections.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-grid#181]
These do not seem to appear for my testcases but they will pop up eventually. Therefore we need to treat them similar as the connections represented by the well perforations.

**Comment by atgeirr** [comment]
I agree that this will be necessary, but doubt we will fix this before the upcoming release. I have therefore put it in the next release milestone. If you are working on this we could of course change that.

**Comment by blattms** [comment]
> If you are working on this we could of course change that.

No, it is just meant as a reminder.

**Comment by atgeirr** [comment]
It's been a year, the issue is still unresolved (and you probably still have no test-cases with it). Keeping the reminder.

**Comment by blattms** [comment]
With the new refactoring of the NNC handling this is not an issue any more, since NNCs will always be repesented by
the CpGrid. Feel free to reopen if you disagree.
