### ISSUE TITLE
Reassigning wells to another process after loadbalance might break constraints.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-grid#231]
We try to force the loadbalancer to keep all cells perforated by a well on one process. After it has run we check that this constraint holds. In the case of one well perforating cells assigned to more than one processor we reassign these cells to the one that perforates the most cells. In the case that a cell is perforated by multiple wells this approach might break the constraint for this cell due to moving it to a new process but leaving all other perforated ones on the old process.

To the very least we should run another check of the constraint and throw an exception if it does not hold. A better approach would be search multiply perforated cells and although use wells that perforate cells of this well into account.

**Comment by atgeirr** [comment]
I agree this bug should be fixed, but I don't think it is extremely urgent, so I will not consider it required for the upcoming release (notify if you disagree).

**Comment by blattms** [comment]
We already do the check. If we find a well scattered between processors, we manually move it to one of them.
