### ISSUE TITLE
Compile failure with MPI but no ZOLTAN

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-grid#235]
I get the following error:
```
/Users/atgeirr/opm-build-debug/opm-grid/dune/grid/cpgrid/CpGrid.cpp:129:40: error: use of undeclared identifier 'part_and_wells'
    return std::make_pair(true, get<1>(part_and_wells));
```
The part_and_wells variable is only defined in the HAVE_ZOLTAN part of the code.

**Comment by GitPaean** [comment]
I did not see this when compiling with the master branch yesterday and today.

**Comment by GitPaean** [comment]
Sorry, I misread your title and did not see `NO ZOLTAN`.

**Comment by blattms** [comment]
Thanks for the report. I am on it.
