### ISSUE TITLE
[Discussion] Moving files to proper directories

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-grid#306]
The current directory structure and organization of this module leaves a lot to be desired. Main points:
 - We put lots of code in the dune/ subdir, this is somewhat misleading as this is not a Dune core module. (Tangentially: we also put code in the Dune namespace, I think that is unfortunate for the same reason)
 - The opm/core subdir should die, and code from there moved to more specific dirs.

Starting point: I suggest to move all dune/grid/ files to opm/grid, and similarly move opm/core/grid/ files also to opm/grid. Also opm/core/<something> to opm/grid/<something>. In the end all files would be in opm/grid.

**Comment by andlaus** [comment]
I agree with all your suggestions if the files end up in `opm/grid` ;).

**Comment by atgeirr** [comment]
> files end up in opm/grid ;).

I intend them to end up in subdirs of opm/grid, not all in opm/grid directly.

**Comment by andlaus** [comment]
that's okay, you just had a typo ;)

**Comment by atgeirr** [comment]
> that's okay, you just had a typo ;)

Ah, fixed...

**Comment by atgeirr** [comment]
Since there are no other comments, I'll make a proposal PR.
