### ISSUE TITLE
opm-grid cannot partition the SPE-10 grid

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-grid#316]
when trying to run the SPE10_MODEL2 deck that is shipped with opm-data on four cores and with ZOLTAN and PTScotch installed, I get this:

```
> mpirun -np 4 ./bin/flow output_dir=. SPE10_MODEL2.DATA

**********************************************************************
*                                                                    *
*                      This is flow 2018.04-pre                      *
*                                                                    *
* Flow is a simulator for fully implicit three-phase black-oil flow, *
*             including solvent and polymer capabilities.            *
*          For more information, see http://opm-project.org          *
*                                                                    *
**********************************************************************

After loadbalancing process 0 has 322630 cells.
```

I've waited for several hours but nothing further happened while the four cores stayed busy. I used the latest dune 2.5 git branch and an optimized build on ubuntu 16.04, i.e. GCC 5.4.0 in conjunction with `-O3 -march=native -DNDEBUG` on a Haswell CPU.

**Comment by GitPaean** [comment]
I can confirm this on my build with the current master branch too.

**Comment by andlaus** [comment]
@atgeirr, @blattms: are there any plans to look into this before the 2018.04 release? it worries me that parallel CpGrid does not work properly with such a simple (albeit largeish) grid.

**Comment by andlaus** [comment]
I just investigated this a bit. I'm pretty sure that it is caused by an MPI desynchronization issue within `CpGrid::loadBalance`: the master process stops at an `MPI_Allreduce` in the initialization routines of the problem while the remaining processes grind to a halt at `CpGrid.cpp:151`. Also, I would be a bit surprised if this problem does not occur for some real-world decks...

**Comment by blattms** [comment]
This really looked familiar and indeed it is solved upstream with the merge of https://gitlab.dune-project.org/core/dune-common/merge_requests/416 and thus is in DUNE 2.5.2 and 2.6.0.

Unfortunately, there is no nice way to fix this here. It it either 
- ship our own copy of variablesizecommunicator.hh, or
- simply make sure the buffer is big enough to always hold one send and waste some memory.

I would opt for the latter. Opinions?

**Comment by atgeirr** [comment]
> simply make sure the buffer is big enough to always hold one send and waste some memory

How much would we waste typically? If only minor I agree this can be a good workaround.
