### ISSUE TITLE
Installation problem opm-grid

### ISSUE THREAD

**Issue by felixfeldmann** [OPM/opm-grid#345]
Dear All, 
I was able to install dune-common-2.6.0, dune-geometry-2.6.0, dune-grid-2.6.0, dune-istl-2.6.0, dune-localfunctions-2.6.0 and dune-typetree-2.6.0. 
After the successful installation of opm-common (10.2017) and opm-material (10.2017), I however fail to add opm-grid (10.217), as i get following issue:
```
CMake Error at /home/felix/workspace/dune/opm-common-release-2017.10/cmake/Modules/OpmPackage.cmake:85 (find_package):
  Could not find a package configuration file provided by "dune-grid" with
  any of the following names:

    dune-gridConfig.cmake
    dune-grid-config.cmake
```
Any idea to solve this problem?
Thank you
Felix

**Comment by felixfeldmann** [comment]
I tried to combine dumux 2.12 with dune 2.6 (which worked fine), and now i am trying to include opm-grid (10.2107) based on the suggestion below:

https://git.iws.uni-stuttgart.de/dumux-repositories/dumux/blob/master/CHANGELOG.md

Which version combination of dune and opm are you recommending? I also tried to install opm-grid (04.2018) but received a similar error message as reported in my earlier comment.

**Comment by akva2** [comment]
to be clear: you are not seeing issues with dune 2.6 just yet, you still have a configuration problem. 

so let's focus on that first. i repeat my statement: i need more info. build logs, configuration logs etc etc. where did you install dune? is it in your prefix paths?

**Comment by felixfeldmann** [comment]
-- CMake version: 3.12.2
-- Linux distribution: Ubuntu 18.04.1 LTS
-- Target architecture: x86_64
-- Source code repository: not found!
-- Linker: ld 2.30
-- Precompiled headers: disabled
-- Build type: Release
-- OpenMP: disabled
-- Could NOT find CppCheck (missing: CPPCHECK_PROGRAM) 
-- Disabling clang-check as CMAKE_EXPORT_COMPILE_COMMANDS is not enabled
-- Finding package C99 using module mode
-- Finding package CXX11Features using module mode
-- Finding package Boost using module mode
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   system
--   unit_test_framework
-- Finding package dune-common using module mode
CMake Warning (dev) at /home/felix/workspace/dune/opm-common-release-2017.10/cmake/Modules/OpmFind.cmake:167 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable dune-common_ROOT is set to:

    /home/felix/workspace/dune/dune-common-2.6.0/build-cmake

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  /home/felix/workspace/dune/opm-common-release-2017.10/cmake/Modules/OpmFind.cmake:235 (find_and_append_package_to)
  /home/felix/workspace/dune/opm-common-release-2017.10/cmake/Modules/OpmLibMain.cmake:122 (find_and_append_package_list_to)
  CMakeLists.txt:108 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Finding package BLAS using module mode
-- Finding package LAPACK using module mode
-- A library with LAPACK API found.
-- Finding package CxaDemangle using module mode
-- Version 2.5.1 of dune-common from /usr/lib/dunecontrol/dune-common/dune.module
-- Finding package dune-grid using module mode
CMake Warning (dev) at /home/felix/workspace/dune/opm-common-release-2017.10/cmake/Modules/OpmFind.cmake:167 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable dune-grid_ROOT is set to:

    /home/felix/workspace/dune/dune-grid-2.6.0/build-cmake

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  /home/felix/workspace/dune/opm-common-release-2017.10/cmake/Modules/OpmFind.cmake:235 (find_and_append_package_to)
  /home/felix/workspace/dune/opm-common-release-2017.10/cmake/Modules/OpmLibMain.cmake:122 (find_and_append_package_list_to)
  CMakeLists.txt:108 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /home/felix/workspace/dune/opm-common-release-2017.10/cmake/Modules/OpmPackage.cmake:85 (find_package):
  Could not find a package configuration file provided by "dune-grid" with
  any of the following names:

    dune-gridConfig.cmake
    dune-grid-config.cmake

  Add the installation prefix of "dune-grid" to CMAKE_PREFIX_PATH or set
  "dune-grid_DIR" to a directory containing one of the above files.  If
  "dune-grid" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /home/felix/workspace/dune/opm-common-release-2017.10/cmake/Modules/Finddune-grid.cmake:17 (find_opm_package)
  /home/felix/workspace/dune/opm-common-release-2017.10/cmake/Modules/OpmFind.cmake:167 (find_package)
  /home/felix/workspace/dune/opm-common-release-2017.10/cmake/Modules/OpmFind.cmake:235 (find_and_append_package_to)
  /home/felix/workspace/dune/opm-common-release-2017.10/cmake/Modules/OpmLibMain.cmake:122 (find_and_append_package_list_to)
  CMakeLists.txt:108 (include)


-- Configuring incomplete, errors occurred!
See also "/home/felix/workspace/dune/opm-grid-release-2017.10/build-cmake/CMakeFiles/CMakeOutput.log".
See also "/home/felix/workspace/dune/opm-grid-release-2017.10/build-cmake/CMakeFiles/CMakeError.log".
--- Failed to build opm-grid ---
Terminating dunecontrol due to previous errors!

**Comment by felixfeldmann** [comment]
i am basically using linux for the first time, so i am very sorry in case i am not able to provide you the right information.

**Comment by akva2** [comment]
you are using dune-control. that's not really how you are supposed to build opm.

anyways, your cmake is not compatible with dune 2.6. its config files relies on the usage of XXX_ROOT variables (long since deprecated in cmake). to make it work you either have to set the policy it warns you to OLD by adding
```cmake
cmake_policy(CMP0074 OLD)
```
at the top of the relevant CMakeLists.txt

alternatively you can pass -Ddune-common_DIR=/home/felix/workspace/dune/dune-common-2.6.0/build-cmake 
```
CMAKE_FLAGS = -Ddune-common_DIR=/home/felix/workspace/dune/dune-common-2.6.0/build-cmake -Ddune-grid_DIR=/home/felix/workspace/dune/dune-grid-2.6.0/build-cmake
```
(extras in the opts file you use for dune-control)

or use installation based builds instead.

**Comment by akva2** [comment]
works for me (tm). i had to patch opm-grid for a missing include (probably due to my bumped compiler).

i have pushed the script and patch here; https://github.com/akva2/opm-grid/tree/example_build_script - see top commit.

if this does not help, i don't know what else i can do.

**Comment by blattms** [comment]
Closing this as it seems stale and rather old. Feel free to reopen if there are still problems.
