### ISSUE TITLE
build from source failing with "Could NOT find dune-grid"

### ISSUE THREAD

**Issue by dhan16** [OPM/opm-grid#348]
I have the following dune modules checked out on releases/2.6:
dune-common dune-istl dune-geometry dune-grid 

for opm, i have the following in master branch as siblings of the dune modules above:
libecl opm-common opm-material opm-grid ewoms opm-simulators

I built the dune modules first one by one with the following code:
```
cd <module>
mkdir cmake-build-debug
cd cmake-build-debug
cmake  -DCMAKE_BUILD_TYPE=Debug .. -G Ninja
ninja
```
This succeeds. 

I then did exactly the same for the opm modules. These succeed:libecl opm-common opm-material

However, opm-grid fails on the make step. Below is the last part of the output. Notice how it finds dune-common and dune-geometry but fails in dune-grid. (even though dune-grid/cmake-build-debug/lib/libdunegrid.a does exist and was build in the dune build steps above):
```
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
-- Performing Test HAVE_CXA_DEMANGLE
-- Performing Test HAVE_CXA_DEMANGLE - Failed
-- Could NOT find CxaDemangle (missing: HAVE_CXA_DEMANGLE) 
-- Performing Test HAVE_DUNE_COMMON
-- Performing Test HAVE_DUNE_COMMON - Success
-- Found dune-common: /Users/dhan/work/opm/dune-common  
-- Version 2.6.0 of dune-common from /Users/dhan/work/opm/dune-common/cmake-build-debug
-- Performing Test HAVE_DUNE_GEOMETRY
-- Performing Test HAVE_DUNE_GEOMETRY - Success
-- Found dune-geometry: /Users/dhan/work/opm/dune-geometry;/Users/dhan/work/opm/dune-common  
-- Version 2.6.0 of dune-geometry from /Users/dhan/work/opm/dune-geometry/cmake-build-debug
-- Could NOT find dune-uggrid (missing: dune-uggrid_DIR)
-- Performing Test HAVE_DUNE_UGGRID
-- Performing Test HAVE_DUNE_UGGRID - Failed
-- Could NOT find dune-uggrid (missing: dune-uggrid_FOUND) 
-- Performing Test HAVE_DUNE_GRID
-- Performing Test HAVE_DUNE_GRID - Success
CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find dune-grid (missing: dune-grid_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /Users/dhan/work/opm/opm-common/cmake/Modules/OpmPackage.cmake:134 (find_package_handle_standard_args)
  /Users/dhan/work/opm/opm-common/cmake/Modules/Finddune-grid.cmake:17 (find_opm_package)
  /Users/dhan/work/opm/opm-common/cmake/Modules/OpmFind.cmake:180 (find_package)
  /Users/dhan/work/opm/opm-common/cmake/Modules/OpmPackage.cmake:172 (find_and_append_package_to)
  opm-grid-prereqs.cmake:37 (find_package_deps)
  CMakeLists.txt:70 (include)
```

**Comment by dhan16** [comment]
hmm. is it interesting that there is a opm-common/cmake-build-debug/include but there isn't a dune-grid/cmake-build-debug/include. it looks like the dune-grid include files dont get copied into the build dir.

**Comment by bska** [comment]
Just one more datapoint.  I noticed a similar symptom in some of my builds shortly after OPM/opm-common#505 (concerning linker issues with Alberta grid) was merged into master.  Locally reverting that PR restored my build, but it is not clear to me at this time what the underlying issue might be.

**Comment by alfbr** [comment]
Ah, I got the same error and was oblivious to why. Will check reverting.

**Comment by GitPaean** [comment]
>  I noticed a similar symptom in some of my builds shortly after OPM/opm-common#505

Same here.

**Comment by bska** [comment]
> identified the problem in OPM/opm-common#505 on Friday

Okay, good.  But why did this not fail Jenkins?  Does Jenkins have Alberta?

**Comment by blattms** [comment]
@dhan16 does the problem persist after the merge of OPM/opm-common#525?

**Comment by dhan16** [comment]
So I was trying to reproduce the problem with Alberta actually - trying to gauge why we need findAlberta. I did the following change and built everything (basically I removed Alberta). Then I ran flow_legacy and it ran!

./flow_legacy /Users/dhan/work/opm/flow/cases/spe1/SPE1.DATA output_dir=spe1_1

How can I reproduce the original problem you faced? I'm curious what it was and would like to have a shot at fixing it without pulling in Alberta. 

[dhan@20:54:46 Wed Oct 17 opm-common]git diff
diff --git a/cmake/Modules/Finddune-grid.cmake b/cmake/Modules/Finddune-grid.cmake
index be6f4e4c..958ced9e 100644
--- a/cmake/Modules/Finddune-grid.cmake
+++ b/cmake/Modules/Finddune-grid.cmake
@@ -28,7 +28,6 @@ find_opm_package (
   dune-uggrid;
   MPI;
   UG;
-  Alberta
   "
   # header to search for
   "dune/grid/onedgrid.hh"
@@ -57,7 +56,6 @@ int main (void) {
    HAVE_ALBERTA;
    HAVE_STDINT_H;
    DUNE_GRID_EXPERIMENTAL_GRID_EXTENSIONS;
-   DUNE_ALBERTA_VERSION
   ")
 
 #debug_find_vars ("dune-grid")

**Comment by dhan16** [comment]
checked with the latest fix. it does build now. still curious though about the report for original error as it would be good to fix this without FindAlberta.

**Comment by blattms** [comment]
BTW I might have activated the building the tests in ewoms ( cmake -DBUILD_TESTING=ON) when I experienced this (default is off). That would be a sound explanation why this usually does not happen.

**Comment by andlaus** [comment]
I am not aware of any tests in eWoms that use Alberta, even if it is successfully detected.

**Comment by dhan16** [comment]
@blattms Thanks. I'll try to reproduce (I only have a Mac but I am hoping that doesn't matter). What seems to stand out to me is that you had Alberta installed. There's probably funny code in dune which picks up Alberta if it seems it as installed. 

I'm closing this issue itself as the compilation error is fixed. Thanks
