### ISSUE TITLE
opm-grid seems to depend on opm-common but is only listed under "suggests"

### ISSUE THREAD

**Issue by timokoch** [OPM/opm-grid#353]
The file `opm-grid-prereqs.cmake` uses the CMake macro `find_package_deps` which is defined in `opm-common`. So opm-grid depends on opm-common but in `dune.module` it is only listed under `suggests`.

An error occurred in the following setting: Module A suggests (and finds) `opm-grid`, Module B depends on module A (but not on OPM at all); configuring Module B leads to the following CMake error:

```
CMake Error at /home/timok/dumux-course/opm-grid/opm-grid-prereqs.cmake:37 (find_package_deps):
  Unknown CMake command "find_package_deps".
```

I tested version release 2018.10 and used `dunecontrol`. Shouldn't `opm-grid` __depend__ on `opm-common` in that case? At least the call would need an if guard if `opm-common` is really optional.

**Comment by blattms** [comment]
Fixed via #396
