### ISSUE TITLE
local ids not persistent across loadbalancing

### ISSUE THREAD

**Issue by blattms** [OPM/opm-grid#454]
The way the locel id set is currently implement, the ids get computed by based on the number of entities there are for each codim. Since this number changes when loadbalancing, the ids change too.
This is a violation of the DUNE grid interface that requires ids to be consistent across grid changes. It will prevent people from using their usual approach of distributing data.

This was also the reason for the differing well curves in OPM/opm-simulators#2406 where we used one unordered map with local ids as keys to store the values to send and the same map for receiving them.

**Comment by atgeirr** [comment]
So happy you discovered the cause! Should we use ids based on cartesian indices instead?

**Comment by blattms** [comment]
Well, the quick (and clean fix) would be to return our `GlobalIdSet` also for ``CpGrid::localIdSet()` it has all the needed properties and the additional one the id is globally unique (as in across all processors) does not hurt.

What do you think?

We could of course also make `GlobalIdSet` use the cartesian index for the cells but that will be more effort since we need to rewrite some stuff. Was'nt there a situation when there were no global indices?

**Comment by atgeirr** [comment]
I must admit I am a bit lost here. I do not really know the difference between local and global ID sets, I thought Ids were global and Indexes were local. So perhaps you should not listen to my suggestions about this.

**Comment by blattms** [comment]
ids are persistent across grid modifications.
For the local id set this persistence is only on the same process. E.g. if after loadbalance the enitity stays on the same process it has to have the same id. If it moves to another process the id is allowed to change.

For the global id set the same entity has the same id no matter whether is moves or not.

**Comment by atgeirr** [comment]
Thanks for the explanation!
