### ISSUE TITLE
Please deactivate aquifer processing if no aquifer is there.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-grid#528]
In [processesEclipseFormat.cpp:268]OPM/opm-grid/blob/c65d0e6f92aa229e1306145d705149a56484de51/opm/grid/cpgrid/processEclipseFormat.cpp#L268-L271) we create a global array `is_aquifer_cell` even if `aquifer` and `aquifer_cell_volumes` is empty. 

Is that really needed? We can't we in this case skip creating the global array and pass a `nullptr` instead? Shouldn't this save some work and memory?

**Comment by GitPaean** [comment]
Sure. I will take a look now.
